name: 'genshin check in'
description: 'genshin check in'
inputs:
  who-to-greet:  # id of input
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: './index.js'
  